name = "Symplectic"
uuid = "32b24f23-0065-419a-aebb-272ab3b73786"
authors = ["Mengzhen-Zhang <me@menngzhen-zhang.org>"]
version = "0.1.0"

[deps]
JSON = "0.21.3"
Optim = "1.7.1"
ReverseDiff = "1.14.1"

[compat]
julia = "1.7.3"